name: Deployment (Single Job)
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: latest
      - name: Install Dependencies
        run: npm ci
      - name: Linting...
        run: npm run lint
      - name: Testing...
        run: npm run test
      - name: Building...
        run: npm run build
      - name: Deploying...
        run: echo "Deploying..."
